[project]
name = "quanten-computing-fp"
version = "0.1.0"
description = "This repo is for my labcourse"
readme = "README.md"
authors = [
    { name = "Pascal", email = "st183508@stud.uni-stuttgart.de" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.3",
]

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
